services:
  postgres:
    image: postgres:16.9
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: main_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    command: npm run start:dev auth-service
    container_name: auth-service
    depends_on:
      - postgres
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    command: npm run start:dev api-gateway
    container_name: api-gateway
    depends_on:
      - auth-service
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:
    driver: local
